= OSGi Key concepts

I won't give here a detailed explanation what OSGi is. There are a lot of good explanations out there. For a great overviesw I can recommend the RefCard link:https://dzone.com/storage/assets/4263-rc037-010d-equinox.pdf[Getting Started with Equinox & OSGi] written by Jeff McAffer. It is about using equinox which is an implementation of the OSGi specification. You might need to register to read the card. It is free and gives you access to great content.

At this place I highly recommend to download the OSGi specs. They are well written and a great source to find out how thinks are (at least) supposed to work:
link:http://www.osgi.org/Download/HomePage[OSGi Spec Downloads]

Here is what the specification says what the OSGi framework is:

[quote, OSGi Alliance, OSGi Core Specification 6, p.9]
____________________________________________________________________
It provides a general-purpose, secure, and
managed Java framework that supports the deployment of extensible and downloadable applications
known as bundles.
____________________________________________________________________

It is important to understand that the OSGi world distinguishes between different specifications. For Release 5 in 2012 there were 2 specifications:

1. OSGi Core and 
1. OSGi Enterprise

Since Release 6 the specifications have been reorganized into:

OSGi Core (June 2014):: Defines the basic framework. Basically it covers the definition of 
* bundles
* their lifecycle (installation, resolution, starting, etc.)
* dependencies between bundles and their resolution
* certain APIs to interact with the OSGi container.
OSGi Enterprise (July 2015):: The enterprise specification drives to integrate Java EE features into the OSGi framework. In this specification services are defined that cover JavaEE aspects like:
* JTA container managed transactions,
* JDBC Driver management and
* services for logging, administration, configuration, ReST, etc.
OSGi Residential (July 2015):: Specifies an API for large scale remote management of OSGi framework and their applications/services.
OSGi Compendium (July 2015):: Is the compendium of all OSGi service specifications.

== Basic Terminology
The core component an OSGi framework handles is the so called _bundle_.
In general a bundle is a simple jar file that inlcudes OSGi-specific *headers* within its *META-INF/MANIFEST.mf* file.

The core specification R6 lists 23 headers. 


== Basic Provisioning of an OSGi Container

* Starting and stopping a container
* using the apache gogo shell

== Some thoughts on IDEs
If you are coming from Web Development, no matter which of the big Java IDEs Intellij, Eclipse, Netbeans you use: if you develop Maven based Java EE Applications whether WAR or EAR projects you get a quite good support from your IDE. Also Spring is widly supported within the IDEs e.g. giving you code completion in spring xml configuration or hints in source files.

For OSGi development it looks different. If you are looking for plugins only Eclipse offers a good plugin solution link:http://bndtools.org/[Bnd Tools]. It is also used within the book from O'Reilly: link:http://shop.oreilly.com/product/0636920028086.do[Building Modular Cloud Apps with OSGi].

But if you are used to develop software using Maven (or any other build tool capable of resolving dependencies) then you will face the first wall the needs to be taken.
In the beginning Bndtools felt quite good, allthough it differs from developing maven projects.
Netbeans has some kind of support if you develop Netbeans Modules. But I ended up using plain Maven projects, because those can run in a general CI environment with Maven support out of the box.
About OSMORC the OSGi plugin from Intellij I cannot say anything because I have not used it.
